//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRA_SCHOOL.RESOURCES.US {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class enUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal enUS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BRA_SCHOOL.RESOURCES.US.enUS", typeof(enUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ativo {
            get {
                return ResourceManager.GetString("ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbor:.
        /// </summary>
        internal static string bairro {
            get {
                return ResourceManager.GetString("bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string bloqueado {
            get {
                return ResourceManager.GetString("bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancela {
            get {
                return ResourceManager.GetString("cancela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string cidade {
            get {
                return ResourceManager.GetString("cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm:.
        /// </summary>
        internal static string confirmacao {
            get {
                return ResourceManager.GetString("confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail:.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string endereco {
            get {
                return ResourceManager.GetString("endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string exportar {
            get {
                return ResourceManager.GetString("exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string fechar {
            get {
                return ResourceManager.GetString("fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Neighborhood - [Qtd] ::.
        /// </summary>
        internal static string frmBairro {
            get {
                return ResourceManager.GetString("frmBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Cities - [Qtd] ::.
        /// </summary>
        internal static string frmCidade {
            get {
                return ResourceManager.GetString("frmCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Courses - [Qtd] ::.
        /// </summary>
        internal static string frmCurso {
            get {
                return ResourceManager.GetString("frmCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Address - [Qtd] ::.
        /// </summary>
        internal static string frmEndereco {
            get {
                return ResourceManager.GetString("frmEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of States - [Qtd] ::.
        /// </summary>
        internal static string frmEstado {
            get {
                return ResourceManager.GetString("frmEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: File Export ::.
        /// </summary>
        internal static string frmExport {
            get {
                return ResourceManager.GetString("frmExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Acctions - [Qtd] ::.
        /// </summary>
        internal static string frmFuncionalidade {
            get {
                return ResourceManager.GetString("frmFuncionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Groups - [Qtd] ::.
        /// </summary>
        internal static string frmGrupo {
            get {
                return ResourceManager.GetString("frmGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Login ::.
        /// </summary>
        internal static string frmLogin {
            get {
                return ResourceManager.GetString("frmLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Type Street - [Qtd] ::.
        /// </summary>
        internal static string frmLogradouro {
            get {
                return ResourceManager.GetString("frmLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Matter - [Qtd] ::.
        /// </summary>
        internal static string frmMateria {
            get {
                return ResourceManager.GetString("frmMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Teacher Level - [Qtd] ::.
        /// </summary>
        internal static string frmNivelProfessor {
            get {
                return ResourceManager.GetString("frmNivelProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Countries - [Qtd] ::.
        /// </summary>
        internal static string frmPais {
            get {
                return ResourceManager.GetString("frmPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Teachers - [Qtd] ::.
        /// </summary>
        internal static string frmProfessor {
            get {
                return ResourceManager.GetString("frmProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Roons - [Qtd] ::.
        /// </summary>
        internal static string frmSala {
            get {
                return ResourceManager.GetString("frmSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Unities - [Qtd] ::.
        /// </summary>
        internal static string frmUnidade {
            get {
                return ResourceManager.GetString("frmUnidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Manage of Users - [Qtd] ::.
        /// </summary>
        internal static string frmUsuario {
            get {
                return ResourceManager.GetString("frmUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string gravar {
            get {
                return ResourceManager.GetString("gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string logar {
            get {
                return ResourceManager.GetString("logar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string mnuAjuda {
            get {
                return ResourceManager.GetString("mnuAjuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string mnuArquivo {
            get {
                return ResourceManager.GetString("mnuArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        internal static string mnuBairro {
            get {
                return ResourceManager.GetString("mnuBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string mnuCadastro {
            get {
                return ResourceManager.GetString("mnuCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascade.
        /// </summary>
        internal static string mnuCascata {
            get {
                return ResourceManager.GetString("mnuCascata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string mnuCidade {
            get {
                return ResourceManager.GetString("mnuCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        internal static string mnuCurso {
            get {
                return ResourceManager.GetString("mnuCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data od Address.
        /// </summary>
        internal static string mnuDadosEndereco {
            get {
                return ResourceManager.GetString("mnuDadosEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string mnuEncerrar {
            get {
                return ResourceManager.GetString("mnuEncerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string mnuEndereco {
            get {
                return ResourceManager.GetString("mnuEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string mnuEstado {
            get {
                return ResourceManager.GetString("mnuEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string mnuExportacoes {
            get {
                return ResourceManager.GetString("mnuExportacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        internal static string mnuFecharTodos {
            get {
                return ResourceManager.GetString("mnuFecharTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string mnuHorizontal {
            get {
                return ResourceManager.GetString("mnuHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string mnuJanela {
            get {
                return ResourceManager.GetString("mnuJanela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Street.
        /// </summary>
        internal static string mnuLogradouro {
            get {
                return ResourceManager.GetString("mnuLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter.
        /// </summary>
        internal static string mnuMateria {
            get {
                return ResourceManager.GetString("mnuMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Teacher.
        /// </summary>
        internal static string mnuNivelProfessor {
            get {
                return ResourceManager.GetString("mnuNivelProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string mnuPais {
            get {
                return ResourceManager.GetString("mnuPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo.
        /// </summary>
        internal static string mnuPeriodo {
            get {
                return ResourceManager.GetString("mnuPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string mnuProfessor {
            get {
                return ResourceManager.GetString("mnuProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relats.
        /// </summary>
        internal static string mnuRelatorio {
            get {
                return ResourceManager.GetString("mnuRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string mnuSala {
            get {
                return ResourceManager.GetString("mnuSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More ....
        /// </summary>
        internal static string mnuSobre {
            get {
                return ResourceManager.GetString("mnuSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string mnuTurma {
            get {
                return ResourceManager.GetString("mnuTurma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity.
        /// </summary>
        internal static string mnuUnidade {
            get {
                return ResourceManager.GetString("mnuUnidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string mnuUsuario {
            get {
                return ResourceManager.GetString("mnuUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string mnuVertical {
            get {
                return ResourceManager.GetString("mnuVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        internal static string nivel {
            get {
                return ResourceManager.GetString("nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string novo {
            get {
                return ResourceManager.GetString("novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string pesquisar {
            get {
                return ResourceManager.GetString("pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Format and folder for file.
        /// </summary>
        internal static string selecionaArquivo {
            get {
                return ResourceManager.GetString("selecionaArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity:.
        /// </summary>
        internal static string unidade {
            get {
                return ResourceManager.GetString("unidade", resourceCulture);
            }
        }
    }
}
